# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'addon_manager.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_winAddonManager(object):
    def setupUi(self, winAddonManager):
        if not winAddonManager.objectName():
            winAddonManager.setObjectName(u"winAddonManager")
        winAddonManager.setWindowModality(Qt.ApplicationModal)
        winAddonManager.resize(720, 400)
        font = QFont()
        font.setFamilies([u"Verdana"])
        font.setPointSize(12)
        winAddonManager.setFont(font)
        winAddonManager.setModal(True)
        self.actionAddonImport = QAction(winAddonManager)
        self.actionAddonImport.setObjectName(u"actionAddonImport")
        self.actionShowOnLotrointerface = QAction(winAddonManager)
        self.actionShowOnLotrointerface.setObjectName(u"actionShowOnLotrointerface")
        self.actionShowSelectedOnLotrointerface = QAction(winAddonManager)
        self.actionShowSelectedOnLotrointerface.setObjectName(u"actionShowSelectedOnLotrointerface")
        self.actionInstallAddon = QAction(winAddonManager)
        self.actionInstallAddon.setObjectName(u"actionInstallAddon")
        self.actionUninstallAddon = QAction(winAddonManager)
        self.actionUninstallAddon.setObjectName(u"actionUninstallAddon")
        self.actionShowAddonInFileManager = QAction(winAddonManager)
        self.actionShowAddonInFileManager.setObjectName(u"actionShowAddonInFileManager")
        self.actionShowPluginsFolderInFileManager = QAction(winAddonManager)
        self.actionShowPluginsFolderInFileManager.setObjectName(u"actionShowPluginsFolderInFileManager")
        self.actionShowSkinsFolderInFileManager = QAction(winAddonManager)
        self.actionShowSkinsFolderInFileManager.setObjectName(u"actionShowSkinsFolderInFileManager")
        self.actionShowMusicFolderInFileManager = QAction(winAddonManager)
        self.actionShowMusicFolderInFileManager.setObjectName(u"actionShowMusicFolderInFileManager")
        self.actionUpdateAllSelectedAddons = QAction(winAddonManager)
        self.actionUpdateAllSelectedAddons.setObjectName(u"actionUpdateAllSelectedAddons")
        self.actionUpdateAddon = QAction(winAddonManager)
        self.actionUpdateAddon.setObjectName(u"actionUpdateAddon")
        self.actionEnableStartupScript = QAction(winAddonManager)
        self.actionEnableStartupScript.setObjectName(u"actionEnableStartupScript")
        self.actionDisableStartupScript = QAction(winAddonManager)
        self.actionDisableStartupScript.setObjectName(u"actionDisableStartupScript")
        self.btnBox = QDialogButtonBox(winAddonManager)
        self.btnBox.setObjectName(u"btnBox")
        self.btnBox.setGeometry(QRect(541, 367, 169, 27))
        self.btnBox.setStandardButtons(QDialogButtonBox.Close)
        self.txtSearchBar = QLineEdit(winAddonManager)
        self.txtSearchBar.setObjectName(u"txtSearchBar")
        self.txtSearchBar.setGeometry(QRect(260, 17, 371, 27))
        self.txtSearchBar.setClearButtonEnabled(True)
        self.btnAddons = QToolButton(winAddonManager)
        self.btnAddons.setObjectName(u"btnAddons")
        self.btnAddons.setGeometry(QRect(650, 12, 52, 36))
        self.btnAddons.setPopupMode(QToolButton.MenuButtonPopup)
        self.tabWidget = QTabWidget(winAddonManager)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(-4, 29, 731, 331))
        self.tabInstalled = QWidget()
        self.tabInstalled.setObjectName(u"tabInstalled")
        self.tabWidgetInstalled = QTabWidget(self.tabInstalled)
        self.tabWidgetInstalled.setObjectName(u"tabWidgetInstalled")
        self.tabWidgetInstalled.setGeometry(QRect(0, 0, 721, 301))
        self.tabPluginsInstalled = QWidget()
        self.tabPluginsInstalled.setObjectName(u"tabPluginsInstalled")
        self.tablePluginsInstalled = QTableWidget(self.tabPluginsInstalled)
        if (self.tablePluginsInstalled.columnCount() < 6):
            self.tablePluginsInstalled.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.tablePluginsInstalled.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tablePluginsInstalled.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tablePluginsInstalled.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tablePluginsInstalled.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tablePluginsInstalled.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tablePluginsInstalled.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        self.tablePluginsInstalled.setObjectName(u"tablePluginsInstalled")
        self.tablePluginsInstalled.setGeometry(QRect(0, 0, 721, 271))
        self.tablePluginsInstalled.setFrameShape(QFrame.NoFrame)
        self.tablePluginsInstalled.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tablePluginsInstalled.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tablePluginsInstalled.setDragEnabled(False)
        self.tablePluginsInstalled.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tablePluginsInstalled.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tablePluginsInstalled.setSortingEnabled(True)
        self.tablePluginsInstalled.setCornerButtonEnabled(True)
        self.tablePluginsInstalled.horizontalHeader().setVisible(True)
        self.tablePluginsInstalled.horizontalHeader().setCascadingSectionResizes(False)
        self.tablePluginsInstalled.horizontalHeader().setStretchLastSection(True)
        self.tablePluginsInstalled.verticalHeader().setVisible(False)
        self.tabWidgetInstalled.addTab(self.tabPluginsInstalled, "")
        self.tabSkinsInstalled = QWidget()
        self.tabSkinsInstalled.setObjectName(u"tabSkinsInstalled")
        self.tableSkinsInstalled = QTableWidget(self.tabSkinsInstalled)
        if (self.tableSkinsInstalled.columnCount() < 6):
            self.tableSkinsInstalled.setColumnCount(6)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableSkinsInstalled.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableSkinsInstalled.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableSkinsInstalled.setHorizontalHeaderItem(2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableSkinsInstalled.setHorizontalHeaderItem(3, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableSkinsInstalled.setHorizontalHeaderItem(4, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableSkinsInstalled.setHorizontalHeaderItem(5, __qtablewidgetitem11)
        self.tableSkinsInstalled.setObjectName(u"tableSkinsInstalled")
        self.tableSkinsInstalled.setGeometry(QRect(0, 0, 721, 271))
        self.tableSkinsInstalled.setFrameShape(QFrame.NoFrame)
        self.tableSkinsInstalled.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableSkinsInstalled.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableSkinsInstalled.setDragEnabled(False)
        self.tableSkinsInstalled.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableSkinsInstalled.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableSkinsInstalled.setSortingEnabled(True)
        self.tableSkinsInstalled.setCornerButtonEnabled(True)
        self.tableSkinsInstalled.horizontalHeader().setVisible(True)
        self.tableSkinsInstalled.horizontalHeader().setCascadingSectionResizes(False)
        self.tableSkinsInstalled.horizontalHeader().setStretchLastSection(True)
        self.tableSkinsInstalled.verticalHeader().setVisible(False)
        self.tabWidgetInstalled.addTab(self.tabSkinsInstalled, "")
        self.tabMusicInstalled = QWidget()
        self.tabMusicInstalled.setObjectName(u"tabMusicInstalled")
        self.tableMusicInstalled = QTableWidget(self.tabMusicInstalled)
        if (self.tableMusicInstalled.columnCount() < 6):
            self.tableMusicInstalled.setColumnCount(6)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableMusicInstalled.setHorizontalHeaderItem(0, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableMusicInstalled.setHorizontalHeaderItem(1, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableMusicInstalled.setHorizontalHeaderItem(2, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableMusicInstalled.setHorizontalHeaderItem(3, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableMusicInstalled.setHorizontalHeaderItem(4, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableMusicInstalled.setHorizontalHeaderItem(5, __qtablewidgetitem17)
        self.tableMusicInstalled.setObjectName(u"tableMusicInstalled")
        self.tableMusicInstalled.setGeometry(QRect(0, 0, 721, 271))
        self.tableMusicInstalled.setFrameShape(QFrame.NoFrame)
        self.tableMusicInstalled.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableMusicInstalled.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableMusicInstalled.setDragEnabled(False)
        self.tableMusicInstalled.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableMusicInstalled.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableMusicInstalled.setSortingEnabled(True)
        self.tableMusicInstalled.setCornerButtonEnabled(True)
        self.tableMusicInstalled.horizontalHeader().setVisible(True)
        self.tableMusicInstalled.horizontalHeader().setCascadingSectionResizes(False)
        self.tableMusicInstalled.horizontalHeader().setStretchLastSection(True)
        self.tableMusicInstalled.verticalHeader().setVisible(False)
        self.tabWidgetInstalled.addTab(self.tabMusicInstalled, "")
        self.tabWidget.addTab(self.tabInstalled, "")
        self.tabFindMore = QWidget()
        self.tabFindMore.setObjectName(u"tabFindMore")
        self.tabWidgetRemote = QTabWidget(self.tabFindMore)
        self.tabWidgetRemote.setObjectName(u"tabWidgetRemote")
        self.tabWidgetRemote.setGeometry(QRect(0, 0, 721, 301))
        self.tabPlugins = QWidget()
        self.tabPlugins.setObjectName(u"tabPlugins")
        self.tablePlugins = QTableWidget(self.tabPlugins)
        if (self.tablePlugins.columnCount() < 6):
            self.tablePlugins.setColumnCount(6)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tablePlugins.setHorizontalHeaderItem(0, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tablePlugins.setHorizontalHeaderItem(1, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tablePlugins.setHorizontalHeaderItem(2, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tablePlugins.setHorizontalHeaderItem(3, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tablePlugins.setHorizontalHeaderItem(4, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tablePlugins.setHorizontalHeaderItem(5, __qtablewidgetitem23)
        self.tablePlugins.setObjectName(u"tablePlugins")
        self.tablePlugins.setGeometry(QRect(0, 0, 721, 271))
        self.tablePlugins.setFrameShape(QFrame.NoFrame)
        self.tablePlugins.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tablePlugins.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tablePlugins.setDragEnabled(False)
        self.tablePlugins.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tablePlugins.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tablePlugins.setSortingEnabled(True)
        self.tablePlugins.setCornerButtonEnabled(True)
        self.tablePlugins.horizontalHeader().setVisible(True)
        self.tablePlugins.horizontalHeader().setCascadingSectionResizes(False)
        self.tablePlugins.horizontalHeader().setStretchLastSection(True)
        self.tablePlugins.verticalHeader().setVisible(False)
        self.tabWidgetRemote.addTab(self.tabPlugins, "")
        self.tabSkins = QWidget()
        self.tabSkins.setObjectName(u"tabSkins")
        self.tableSkins = QTableWidget(self.tabSkins)
        if (self.tableSkins.columnCount() < 6):
            self.tableSkins.setColumnCount(6)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.tableSkins.setHorizontalHeaderItem(0, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.tableSkins.setHorizontalHeaderItem(1, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tableSkins.setHorizontalHeaderItem(2, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.tableSkins.setHorizontalHeaderItem(3, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.tableSkins.setHorizontalHeaderItem(4, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.tableSkins.setHorizontalHeaderItem(5, __qtablewidgetitem29)
        self.tableSkins.setObjectName(u"tableSkins")
        self.tableSkins.setGeometry(QRect(0, 0, 721, 271))
        self.tableSkins.setFrameShape(QFrame.NoFrame)
        self.tableSkins.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableSkins.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableSkins.setDragEnabled(False)
        self.tableSkins.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableSkins.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableSkins.setSortingEnabled(True)
        self.tableSkins.setCornerButtonEnabled(True)
        self.tableSkins.horizontalHeader().setVisible(True)
        self.tableSkins.horizontalHeader().setCascadingSectionResizes(False)
        self.tableSkins.horizontalHeader().setStretchLastSection(True)
        self.tableSkins.verticalHeader().setVisible(False)
        self.tabWidgetRemote.addTab(self.tabSkins, "")
        self.tabMusic = QWidget()
        self.tabMusic.setObjectName(u"tabMusic")
        self.tableMusic = QTableWidget(self.tabMusic)
        if (self.tableMusic.columnCount() < 6):
            self.tableMusic.setColumnCount(6)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(0, __qtablewidgetitem30)
        __qtablewidgetitem31 = QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(1, __qtablewidgetitem31)
        __qtablewidgetitem32 = QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(2, __qtablewidgetitem32)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(3, __qtablewidgetitem33)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(4, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(5, __qtablewidgetitem35)
        self.tableMusic.setObjectName(u"tableMusic")
        self.tableMusic.setGeometry(QRect(0, 0, 721, 271))
        self.tableMusic.setFrameShape(QFrame.NoFrame)
        self.tableMusic.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableMusic.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableMusic.setDragEnabled(False)
        self.tableMusic.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableMusic.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableMusic.setSortingEnabled(True)
        self.tableMusic.setCornerButtonEnabled(True)
        self.tableMusic.horizontalHeader().setVisible(True)
        self.tableMusic.horizontalHeader().setCascadingSectionResizes(False)
        self.tableMusic.horizontalHeader().setStretchLastSection(True)
        self.tableMusic.verticalHeader().setVisible(False)
        self.tabWidgetRemote.addTab(self.tabMusic, "")
        self.tabWidget.addTab(self.tabFindMore, "")
        self.progressBar = QProgressBar(winAddonManager)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(12, 369, 441, 23))
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)
        self.lblErrors = QLabel(winAddonManager)
        self.lblErrors.setObjectName(u"lblErrors")
        self.lblErrors.setGeometry(QRect(467, 370, 81, 21))
        self.btnLog = QToolButton(winAddonManager)
        self.btnLog.setObjectName(u"btnLog")
        self.btnLog.setGeometry(QRect(550, 369, 51, 24))
        self.btnLog.setProperty("flat", True)
        self.txtLog = QTextEdit(winAddonManager)
        self.txtLog.setObjectName(u"txtLog")
        self.txtLog.setEnabled(True)
        self.txtLog.setGeometry(QRect(10, 10, 701, 341))
        self.txtLog.setUndoRedoEnabled(False)
        self.txtLog.setReadOnly(True)
        self.btnCheckForUpdates = QToolButton(winAddonManager)
        self.btnCheckForUpdates.setObjectName(u"btnCheckForUpdates")
        self.btnCheckForUpdates.setGeometry(QRect(684, 66, 23, 20))
        self.btnCheckForUpdates.setPopupMode(QToolButton.DelayedPopup)
        self.btnCheckForUpdates.setAutoRaise(False)
        self.btnUpdateAll = QPushButton(winAddonManager)
        self.btnUpdateAll.setObjectName(u"btnUpdateAll")
        self.btnUpdateAll.setGeometry(QRect(576, 67, 97, 18))
        self.btnBox.raise_()
        self.tabWidget.raise_()
        self.txtSearchBar.raise_()
        self.btnAddons.raise_()
        self.progressBar.raise_()
        self.lblErrors.raise_()
        self.btnLog.raise_()
        self.btnCheckForUpdates.raise_()
        self.btnUpdateAll.raise_()
        self.txtLog.raise_()

        self.retranslateUi(winAddonManager)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidgetInstalled.setCurrentIndex(0)
        self.tabWidgetRemote.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(winAddonManager)
    # setupUi

    def retranslateUi(self, winAddonManager):
        winAddonManager.setWindowTitle(QCoreApplication.translate("winAddonManager", u"MainWindow", None))
        self.actionAddonImport.setText(QCoreApplication.translate("winAddonManager", u"Import Addons", None))
#if QT_CONFIG(tooltip)
        self.actionAddonImport.setToolTip(QCoreApplication.translate("winAddonManager", u"Import addons from files/archives", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionAddonImport.setShortcut(QCoreApplication.translate("winAddonManager", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionShowOnLotrointerface.setText(QCoreApplication.translate("winAddonManager", u"Show on lotrointerface.com", None))
        self.actionShowSelectedOnLotrointerface.setText(QCoreApplication.translate("winAddonManager", u"Show selected addons on lotrointerface.com", None))
        self.actionInstallAddon.setText(QCoreApplication.translate("winAddonManager", u"Install", None))
        self.actionUninstallAddon.setText(QCoreApplication.translate("winAddonManager", u"Uninstall", None))
        self.actionShowAddonInFileManager.setText(QCoreApplication.translate("winAddonManager", u"Show in file manager", None))
        self.actionShowPluginsFolderInFileManager.setText(QCoreApplication.translate("winAddonManager", u"Show plugins folder in file manager", None))
        self.actionShowSkinsFolderInFileManager.setText(QCoreApplication.translate("winAddonManager", u"Show skins folder in file manager", None))
        self.actionShowMusicFolderInFileManager.setText(QCoreApplication.translate("winAddonManager", u"Show music folder in file manager", None))
        self.actionUpdateAllSelectedAddons.setText(QCoreApplication.translate("winAddonManager", u"Update all selected addons", None))
        self.actionUpdateAddon.setText(QCoreApplication.translate("winAddonManager", u"Update", None))
        self.actionEnableStartupScript.setText(QCoreApplication.translate("winAddonManager", u"Enable startup script", None))
        self.actionDisableStartupScript.setText(QCoreApplication.translate("winAddonManager", u"Disable startup script", None))
        self.txtSearchBar.setPlaceholderText(QCoreApplication.translate("winAddonManager", u"Search here", None))
#if QT_CONFIG(tooltip)
        self.btnAddons.setToolTip(QCoreApplication.translate("winAddonManager", u"<html><head/><body><p>Remove addons</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnAddons.setText(QCoreApplication.translate("winAddonManager", u"-", None))
        ___qtablewidgetitem = self.tablePluginsInstalled.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("winAddonManager", u"ID", None));
        ___qtablewidgetitem1 = self.tablePluginsInstalled.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("winAddonManager", u"Name", None));
        ___qtablewidgetitem2 = self.tablePluginsInstalled.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("winAddonManager", u"Category", None));
        ___qtablewidgetitem3 = self.tablePluginsInstalled.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("winAddonManager", u"Version", None));
        ___qtablewidgetitem4 = self.tablePluginsInstalled.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("winAddonManager", u"Author", None));
        ___qtablewidgetitem5 = self.tablePluginsInstalled.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("winAddonManager", u"Latest Release", None));
        self.tabWidgetInstalled.setTabText(self.tabWidgetInstalled.indexOf(self.tabPluginsInstalled), QCoreApplication.translate("winAddonManager", u"Plugins", None))
        ___qtablewidgetitem6 = self.tableSkinsInstalled.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("winAddonManager", u"ID", None));
        ___qtablewidgetitem7 = self.tableSkinsInstalled.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("winAddonManager", u"Name", None));
        ___qtablewidgetitem8 = self.tableSkinsInstalled.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("winAddonManager", u"Category", None));
        ___qtablewidgetitem9 = self.tableSkinsInstalled.horizontalHeaderItem(3)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("winAddonManager", u"Version", None));
        ___qtablewidgetitem10 = self.tableSkinsInstalled.horizontalHeaderItem(4)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("winAddonManager", u"Author", None));
        ___qtablewidgetitem11 = self.tableSkinsInstalled.horizontalHeaderItem(5)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("winAddonManager", u"Latest Release", None));
        self.tabWidgetInstalled.setTabText(self.tabWidgetInstalled.indexOf(self.tabSkinsInstalled), QCoreApplication.translate("winAddonManager", u"Skins", None))
        ___qtablewidgetitem12 = self.tableMusicInstalled.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("winAddonManager", u"ID", None));
        ___qtablewidgetitem13 = self.tableMusicInstalled.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("winAddonManager", u"Name", None));
        ___qtablewidgetitem14 = self.tableMusicInstalled.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("winAddonManager", u"Category", None));
        ___qtablewidgetitem15 = self.tableMusicInstalled.horizontalHeaderItem(3)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("winAddonManager", u"Version", None));
        ___qtablewidgetitem16 = self.tableMusicInstalled.horizontalHeaderItem(4)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("winAddonManager", u"Author", None));
        ___qtablewidgetitem17 = self.tableMusicInstalled.horizontalHeaderItem(5)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("winAddonManager", u"Latest Release", None));
        self.tabWidgetInstalled.setTabText(self.tabWidgetInstalled.indexOf(self.tabMusicInstalled), QCoreApplication.translate("winAddonManager", u"Music", None))
#if QT_CONFIG(tooltip)
        self.tabWidgetInstalled.setTabToolTip(self.tabWidgetInstalled.indexOf(self.tabMusicInstalled), QCoreApplication.translate("winAddonManager", u"ABC Files", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInstalled), QCoreApplication.translate("winAddonManager", u"Installed", None))
        ___qtablewidgetitem18 = self.tablePlugins.horizontalHeaderItem(0)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("winAddonManager", u"ID", None));
        ___qtablewidgetitem19 = self.tablePlugins.horizontalHeaderItem(1)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("winAddonManager", u"Name", None));
        ___qtablewidgetitem20 = self.tablePlugins.horizontalHeaderItem(2)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("winAddonManager", u"Category", None));
        ___qtablewidgetitem21 = self.tablePlugins.horizontalHeaderItem(3)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("winAddonManager", u"Version", None));
        ___qtablewidgetitem22 = self.tablePlugins.horizontalHeaderItem(4)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("winAddonManager", u"Author", None));
        ___qtablewidgetitem23 = self.tablePlugins.horizontalHeaderItem(5)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("winAddonManager", u"Latest Release", None));
        self.tabWidgetRemote.setTabText(self.tabWidgetRemote.indexOf(self.tabPlugins), QCoreApplication.translate("winAddonManager", u"Plugins", None))
        ___qtablewidgetitem24 = self.tableSkins.horizontalHeaderItem(0)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("winAddonManager", u"ID", None));
        ___qtablewidgetitem25 = self.tableSkins.horizontalHeaderItem(1)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("winAddonManager", u"Name", None));
        ___qtablewidgetitem26 = self.tableSkins.horizontalHeaderItem(2)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("winAddonManager", u"Category", None));
        ___qtablewidgetitem27 = self.tableSkins.horizontalHeaderItem(3)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("winAddonManager", u"Version", None));
        ___qtablewidgetitem28 = self.tableSkins.horizontalHeaderItem(4)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("winAddonManager", u"Author", None));
        ___qtablewidgetitem29 = self.tableSkins.horizontalHeaderItem(5)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("winAddonManager", u"Latest Release", None));
        self.tabWidgetRemote.setTabText(self.tabWidgetRemote.indexOf(self.tabSkins), QCoreApplication.translate("winAddonManager", u"Skins", None))
        ___qtablewidgetitem30 = self.tableMusic.horizontalHeaderItem(0)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("winAddonManager", u"ID", None));
        ___qtablewidgetitem31 = self.tableMusic.horizontalHeaderItem(1)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("winAddonManager", u"Name", None));
        ___qtablewidgetitem32 = self.tableMusic.horizontalHeaderItem(2)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("winAddonManager", u"Category", None));
        ___qtablewidgetitem33 = self.tableMusic.horizontalHeaderItem(3)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("winAddonManager", u"Version", None));
        ___qtablewidgetitem34 = self.tableMusic.horizontalHeaderItem(4)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("winAddonManager", u"Author", None));
        ___qtablewidgetitem35 = self.tableMusic.horizontalHeaderItem(5)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("winAddonManager", u"Latest Release", None));
        self.tabWidgetRemote.setTabText(self.tabWidgetRemote.indexOf(self.tabMusic), QCoreApplication.translate("winAddonManager", u"Music", None))
#if QT_CONFIG(tooltip)
        self.tabWidgetRemote.setTabToolTip(self.tabWidgetRemote.indexOf(self.tabMusic), QCoreApplication.translate("winAddonManager", u"ABC Files", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFindMore), QCoreApplication.translate("winAddonManager", u"Find More", None))
        self.lblErrors.setText(QCoreApplication.translate("winAddonManager", u"Errors: 0", None))
        self.btnLog.setText(QCoreApplication.translate("winAddonManager", u"Log", None))
#if QT_CONFIG(tooltip)
        self.btnCheckForUpdates.setToolTip(QCoreApplication.translate("winAddonManager", u"<html><head/><body><p>Check for updates</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnCheckForUpdates.setText("")
#if QT_CONFIG(tooltip)
        self.btnUpdateAll.setToolTip(QCoreApplication.translate("winAddonManager", u"Update all addons", None))
#endif // QT_CONFIG(tooltip)
        self.btnUpdateAll.setText(QCoreApplication.translate("winAddonManager", u"Update All", None))
    # retranslateUi

