# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'winSetupWizard.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_winGameWizard(object):
    def setupUi(self, winGameWizard):
        if not winGameWizard.objectName():
            winGameWizard.setObjectName(u"winGameWizard")
        winGameWizard.setWindowModality(Qt.ApplicationModal)
        winGameWizard.resize(621, 411)
        font = QFont()
        font.setFamilies([u"Verdana"])
        font.setPointSize(12)
        winGameWizard.setFont(font)
        winGameWizard.setModal(True)
        self.actionShowTest = QAction(winGameWizard)
        self.actionShowTest.setObjectName(u"actionShowTest")
        self.actionShowNormal = QAction(winGameWizard)
        self.actionShowNormal.setObjectName(u"actionShowNormal")
        self.stackedWidget = QStackedWidget(winGameWizard)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(20, 20, 601, 401))
        self.Introduction = QWidget()
        self.Introduction.setObjectName(u"Introduction")
        self.btnBoxIntro = QDialogButtonBox(self.Introduction)
        self.btnBoxIntro.setObjectName(u"btnBoxIntro")
        self.btnBoxIntro.setGeometry(QRect(360, 354, 201, 25))
        self.btnBoxIntro.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.lblIntro = QLabel(self.Introduction)
        self.lblIntro.setObjectName(u"lblIntro")
        self.lblIntro.setGeometry(QRect(16, -117, 501, 361))
        self.lblIntro.setWordWrap(True)
        self.stackedWidget.addWidget(self.Introduction)
        self.GameFinder = QWidget()
        self.GameFinder.setObjectName(u"GameFinder")
        self.btnFind = QToolButton(self.GameFinder)
        self.btnFind.setObjectName(u"btnFind")
        self.btnFind.setGeometry(QRect(409, 82, 141, 51))
        self.btnFind.setPopupMode(QToolButton.MenuButtonPopup)
        self.lstLOTRO = QListWidget(self.GameFinder)
        self.lstLOTRO.setObjectName(u"lstLOTRO")
        self.lstLOTRO.setGeometry(QRect(80, 176, 461, 71))
        self.lblGameDetection = QLabel(self.GameFinder)
        self.lblGameDetection.setObjectName(u"lblGameDetection")
        self.lblGameDetection.setGeometry(QRect(0, 0, 391, 171))
        self.lblGameDetection.setWordWrap(True)
        self.lblGameDetection.setMargin(7)
        self.lstDDO = QListWidget(self.GameFinder)
        self.lstDDO.setObjectName(u"lstDDO")
        self.lstDDO.setGeometry(QRect(80, 266, 461, 71))
        self.lblLOTRO = QLabel(self.GameFinder)
        self.lblLOTRO.setObjectName(u"lblLOTRO")
        self.lblLOTRO.setGeometry(QRect(-10, 176, 91, 71))
        self.lblLOTRO.setAlignment(Qt.AlignCenter)
        self.lblDDO = QLabel(self.GameFinder)
        self.lblDDO.setObjectName(u"lblDDO")
        self.lblDDO.setGeometry(QRect(-10, 266, 91, 71))
        self.lblDDO.setAlignment(Qt.AlignCenter)
        self.btnGameDirLOTRO = QToolButton(self.GameFinder)
        self.btnGameDirLOTRO.setObjectName(u"btnGameDirLOTRO")
        self.btnGameDirLOTRO.setGeometry(QRect(550, 190, 41, 41))
        self.btnGameDirDDO = QToolButton(self.GameFinder)
        self.btnGameDirDDO.setObjectName(u"btnGameDirDDO")
        self.btnGameDirDDO.setGeometry(QRect(550, 280, 41, 41))
        self.btnBoxOptions = QDialogButtonBox(self.GameFinder)
        self.btnBoxOptions.setObjectName(u"btnBoxOptions")
        self.btnBoxOptions.setGeometry(QRect(360, 350, 201, 32))
        self.btnBoxOptions.setOrientation(Qt.Horizontal)
        self.btnBoxOptions.setStandardButtons(QDialogButtonBox.Apply|QDialogButtonBox.Cancel)
        self.stackedWidget.addWidget(self.GameFinder)
        self.btnFind.raise_()
        self.lblLOTRO.raise_()
        self.lblDDO.raise_()
        self.lstLOTRO.raise_()
        self.lstDDO.raise_()
        self.lblGameDetection.raise_()
        self.btnGameDirLOTRO.raise_()
        self.btnGameDirDDO.raise_()
        self.btnBoxOptions.raise_()
        self.GameFinder2 = QWidget()
        self.GameFinder2.setObjectName(u"GameFinder2")
        self.lblGameDetection_2 = QLabel(self.GameFinder2)
        self.lblGameDetection_2.setObjectName(u"lblGameDetection_2")
        self.lblGameDetection_2.setGeometry(QRect(0, 0, 391, 171))
        self.lblGameDetection_2.setWordWrap(True)
        self.lblGameDetection_2.setMargin(7)
        self.lblLOTRO_2 = QLabel(self.GameFinder2)
        self.lblLOTRO_2.setObjectName(u"lblLOTRO_2")
        self.lblLOTRO_2.setGeometry(QRect(-10, 176, 91, 71))
        self.lblLOTRO_2.setAlignment(Qt.AlignCenter)
        self.lblDDO_2 = QLabel(self.GameFinder2)
        self.lblDDO_2.setObjectName(u"lblDDO_2")
        self.lblDDO_2.setGeometry(QRect(-10, 266, 91, 71))
        self.lblDDO_2.setAlignment(Qt.AlignCenter)
        self.lstLOTROTest = QListWidget(self.GameFinder2)
        self.lstLOTROTest.setObjectName(u"lstLOTROTest")
        self.lstLOTROTest.setGeometry(QRect(80, 176, 461, 71))
        self.lstDDOTest = QListWidget(self.GameFinder2)
        self.lstDDOTest.setObjectName(u"lstDDOTest")
        self.lstDDOTest.setGeometry(QRect(80, 266, 461, 71))
        self.btnFind_2 = QToolButton(self.GameFinder2)
        self.btnFind_2.setObjectName(u"btnFind_2")
        self.btnFind_2.setGeometry(QRect(409, 82, 141, 51))
        self.btnFind_2.setPopupMode(QToolButton.MenuButtonPopup)
        self.btnBoxOptions_2 = QDialogButtonBox(self.GameFinder2)
        self.btnBoxOptions_2.setObjectName(u"btnBoxOptions_2")
        self.btnBoxOptions_2.setGeometry(QRect(360, 350, 201, 32))
        self.btnBoxOptions_2.setOrientation(Qt.Horizontal)
        self.btnBoxOptions_2.setStandardButtons(QDialogButtonBox.Apply|QDialogButtonBox.Cancel)
        self.btnGameDirLOTROTest = QToolButton(self.GameFinder2)
        self.btnGameDirLOTROTest.setObjectName(u"btnGameDirLOTROTest")
        self.btnGameDirLOTROTest.setGeometry(QRect(550, 190, 41, 41))
        self.btnGameDirDDOTest = QToolButton(self.GameFinder2)
        self.btnGameDirDDOTest.setObjectName(u"btnGameDirDDOTest")
        self.btnGameDirDDOTest.setGeometry(QRect(550, 280, 41, 41))
        self.stackedWidget.addWidget(self.GameFinder2)

        self.retranslateUi(winGameWizard)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(winGameWizard)
    # setupUi

    def retranslateUi(self, winGameWizard):
        winGameWizard.setWindowTitle(QCoreApplication.translate("winGameWizard", u"Game Set Up Wizard", None))
        self.actionShowTest.setText(QCoreApplication.translate("winGameWizard", u"Show preview clients", None))
        self.actionShowNormal.setText(QCoreApplication.translate("winGameWizard", u"Show normal clients", None))
        self.lblIntro.setText(QCoreApplication.translate("winGameWizard", u"<html><head/><body><p><span style=\" font-weight:600;\">OneLauncher Setup Wizard:</span><br/></p><p>This wizard will quickly take you through the steps needed to get up and running with OneLauncher. </p></body></html>", None))
        self.btnFind.setText(QCoreApplication.translate("winGameWizard", u"Find Games", None))
        self.lblGameDetection.setText(QCoreApplication.translate("winGameWizard", u"<html><head/><body><p><span style=\" font-weight:600;\">Game Detection:</span></p><p>This should detect any standard installations of The Lord of The Rings Online or Dungeons and Dragons Online. Select the installations that you want to use with OneLauncher. If yours doesn't show up you can add it manually with the approipriate \"...\" button.</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.lblLOTRO.setToolTip(QCoreApplication.translate("winGameWizard", u"The Lord of The Rings Online", None))
#endif // QT_CONFIG(tooltip)
        self.lblLOTRO.setText(QCoreApplication.translate("winGameWizard", u"LOTRO", None))
#if QT_CONFIG(tooltip)
        self.lblDDO.setToolTip(QCoreApplication.translate("winGameWizard", u"Dungeons and Dragons Online", None))
#endif // QT_CONFIG(tooltip)
        self.lblDDO.setText(QCoreApplication.translate("winGameWizard", u"DDO", None))
#if QT_CONFIG(tooltip)
        self.btnGameDirLOTRO.setToolTip(QCoreApplication.translate("winGameWizard", u"Manually browse for the game folder. The folder should have lotroclient.exe in it.", None))
#endif // QT_CONFIG(tooltip)
        self.btnGameDirLOTRO.setText(QCoreApplication.translate("winGameWizard", u"...", None))
#if QT_CONFIG(tooltip)
        self.btnGameDirDDO.setToolTip(QCoreApplication.translate("winGameWizard", u"Manually browse for the game folder. The folder should have dndclient.exe in it.", None))
#endif // QT_CONFIG(tooltip)
        self.btnGameDirDDO.setText(QCoreApplication.translate("winGameWizard", u"...", None))
        self.lblGameDetection_2.setText(QCoreApplication.translate("winGameWizard", u"<html><head/><body><p><span style=\" font-weight:600;\">Preview Client Detection:</span></p><p>This should detect any standard preview client installations of The Lord of The Rings Online or Dungeons and Dragons Online. Select the installations that you want to use with OneLauncher. If yours doesn't show up you can add it manually with the approipriate \"...\" button.</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.lblLOTRO_2.setToolTip(QCoreApplication.translate("winGameWizard", u"The Lord of The Rings Online", None))
#endif // QT_CONFIG(tooltip)
        self.lblLOTRO_2.setText(QCoreApplication.translate("winGameWizard", u"LOTRO", None))
#if QT_CONFIG(tooltip)
        self.lblDDO_2.setToolTip(QCoreApplication.translate("winGameWizard", u"Dungeons and Dragons Online", None))
#endif // QT_CONFIG(tooltip)
        self.lblDDO_2.setText(QCoreApplication.translate("winGameWizard", u"DDO", None))
        self.btnFind_2.setText(QCoreApplication.translate("winGameWizard", u"Find Games", None))
#if QT_CONFIG(tooltip)
        self.btnGameDirLOTROTest.setToolTip(QCoreApplication.translate("winGameWizard", u"Manually browse for the game folder. The folder should have lotroclient.exe in it.", None))
#endif // QT_CONFIG(tooltip)
        self.btnGameDirLOTROTest.setText(QCoreApplication.translate("winGameWizard", u"...", None))
#if QT_CONFIG(tooltip)
        self.btnGameDirDDOTest.setToolTip(QCoreApplication.translate("winGameWizard", u"Manually browse for the game folder. The folder should have dndclient.exe in it.", None))
#endif // QT_CONFIG(tooltip)
        self.btnGameDirDDOTest.setText(QCoreApplication.translate("winGameWizard", u"...", None))
    # retranslateUi

