# coding=utf-8
Version = "1.0.0"
Description = "LOTRO/DDO Custom Launcher"
Website = "<a href=\"https://github.com/JeremyStepp/OneLauncher\">Github.com/JeremyStepp/OneLauncher</a>"
Author = "Jeremy Stepp"
Email = "jeremy@bluetecno.com"
WebSite = ""
LongDescription = "Lord of the Rings Online and Dungeons & Dragons Online\nLauncher for Linux, Mac, and Windows"
Copyright = "(C) 2019 Jeremy Stepp"
PyLotROReference = "Based on PyLotRO\n(C) 2009-2010 AJackson"
CLIReference = "Based on CLI launcher for LOTRO\n(C) 2007-2010 SNy"
LotROLinuxReference = "Based on LotROLinux\n(C) 2007-2009 AJackson"
